### ISSUE TITLE
Keep the todo.txt format spec in a separate repo

### ISSUE THREAD

**Issue by zagortenay333** [todotxt/todo.txt-cli-fork#16]
I think that would be more natural than being in the wiki of the cli implementation of it. Especially now that you have an organization.

Or maybe even make a simple github page for it?

**Comment by karbassi** [comment]
@zagortenay333 I agree. Would be nice to have the format in its own repo to discuss patterns and standards.

**Comment by karbassi** [comment]
This issue was moved to todotxt/todo.txt-cli#213
